initial
stutisk/project1-component-library pull request #5
Opened 2022-02-02 18:44 UTC by stutisk

2022-02-02 20:10 UTC, FarhanMobashir reviewed
go through the comments and make the change if it makes sense for you. Thank you

2022-02-02 20:10 UTC, FarhanMobashir commented on components/buttons/button.css
> +
use prettier for code formatting https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2022-02-02 20:10 UTC, FarhanMobashir commented on components/buttons/button.css
> +   font-size: 1.5rem;
make some css variable for the sizes of the font thatt you keep reusing

2022-02-02 20:34 UTC, yogesh- requested changes
Look at the changes suggested in the first review, rest all looks good.

2022-02-03 11:57 UTC, stutisk commented
hey ! i have made the changes , do check it once , thanku

2022-02-03 11:58 UTC, stutisk commented on components/buttons/button.css
> +    --text-color-secondry:black;
hey ,i have added the changes , thanku

2022-02-03 12:05 UTC, merged