Alert
stutisk/project1-component-library pull request #7
Opened 2022-02-06 15:05 UTC by stutisk

https://user-images.githubusercontent.com/48529714/152687163-c9291f9b-df51-47ad-87a8-224426fb4b8a.mp4

2022-02-06 15:11 UTC, dev-enforced commented on docs/spacing.css
> + padding: 25px 60px;
You can use rem instead of px over here.

2022-02-06 15:14 UTC, dev-enforced requested changes
Rest of the code looks good to me.Good work on the docs and alerts @stutisk

2022-02-06 15:14 UTC, dev-enforced commented on docs/spacing.css
> + padding: 25px 60px;
You can use rem instead of px over here.

2022-02-06 15:14 UTC, dev-enforced commented on components/alerts/alerts.css
> +    border-radius: 10px;
You can use this value in the common stylesheet file and use a variable related to border-radius formats so that you can give a fixed border radius to all the appropriate elements.

2022-02-06 15:16 UTC, AnuragSahu11 commented on docs/container.css
> +    border:2px outset #0A7C70;
Use preetify

2022-02-06 15:17 UTC, AnuragSahu11 commented on docs/spacing.css
>   .btn-padding{
You can use rem for anything above 10px

2022-02-06 15:17 UTC, AnuragSahu11 reviewed
Other than that looks good

2022-02-07 10:31 UTC, stutisk commented on docs/spacing.css
> + padding: 25px 60px;
fixed! thanku

2022-02-07 10:31 UTC, stutisk commented on docs/container.css
> +    border:2px outset #0A7C70;
okay thanku

2022-02-07 10:32 UTC, merged